# Generated by Django 6.0.7 on 2026-08-26 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado')], default='aguardando', max_length=20)),
                ('horario_chegada', models.DateTimeField(auto_now_add=True)),
                ('medico_destinado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='membros.medico')),
            ],
            options={
                'ordering': ['horario_chegada'],
            },
        ),
    ]
