# Generated by Django 6.1 on 2026-08-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0002_pacientefila_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientefila',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
